### ISSUE TITLE
creating login session queue is broken

### ISSUE THREAD

**Issue by rscx-r1** [sandbox-pokhara/league-client#21]
i use this library without a riotclient.exe, just on requests, but 

![image](https://github.com/sandbox-pokhara/league-client/assets/53280415/a1195041-d793-4f0b-bddd-eb0166c3a6f7)
rso_ledge.py

 this function is completly broken cos it returns aiohttp.client_exceptions.serverdisconnectederror
 no clue what is this
 
 current situation:
 1. use account_info.get_account_info(*args)
 2. wait some time
 3. got this error
 
 needs:
 1. use account_info.get_account_info(*args)
 2. wait some time
 3. no error, just clean response

**Comment by rscx-r1** [comment]
> I have the same problem.

i think it's server rotate by riots, in http-debugger RU region have Host: euc1-red.pp.sgp.pvp.net
but in script "RU": "https://euc1-green.pp.sgp.pvp.net"

hopefully it solve

**Comment by deniii1753** [comment]
Yeah, it worked, thanks!

**Comment by rscx-r1** [comment]
Created PR what fixes that problem: https://github.com/sandbox-pokhara/league-client/pull/22
