### ISSUE TITLE
Cannot get the Post Friend Request to work

### ISSUE THREAD

**Issue by trackxx** [sandbox-pokhara/league-client#26]
post_friend_request keeps returning false despite valid puu_id;
Am I doing something wrong? 
![frend](https://github.com/sandbox-pokhara/league-client/assets/15087297/c9a4f5e4-5460-4a79-9a56-8dd43ccc18f3)

**Comment by lemon-sandwich** [comment]
I'm having the same issue. My response is 
{'errorCode': 'RESOURCE_NOT_FOUND', 'httpStatus': 404, 'message': 'Invalid URI format'}

**Comment by lemon-sandwich** [comment]
> post_friend_request keeps returning false despite valid puu_id; Am I doing something wrong? ![frend](https://private-user-images.githubusercontent.com/15087297/324188726-c9a4f5e4-5460-4a79-9a56-8dd43ccc18f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDg4ODksIm5iZiI6MTcxNjMwODU4OSwicGF0aCI6Ii8xNTA4NzI5Ny8zMjQxODg3MjYtYzlhNGY1ZTQtNTQ2MC00YTc5LTlhNTYtOGRkNDNjY2MxOGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE2MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MzgzOWExZDRjOGU0NzBkZDBiOGE1N2RmODJhOTAwOGI3ZDFlODNkZmM1N2Q0OGJkNjM2OWQ0OTg2YWVkZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BpnctIfZhcE-1vp3dFKnheYOXMvor2dT7dttuDq2jqM)

Go to the friendrequests.py file and return the res.json instead of res.ok. The API returns a 204 status code. Which basically means that friend request has been sent.

**Comment by pradishb** [comment]
@trackxx The old friend request endpoint seems to have been removed.
