### ISSUE TITLE
Login With Credentials it's not working anymore

### ISSUE THREAD

**Issue by gui-fkb** [sandbox-pokhara/league-client#47]
Maybe riot did something today/yesterday but it looks like login with credentials is not working, i'm getting some cloudfare error.

The error status code is 403, with the following content: 

 '<!DOCTYPE html>
<html class="no-js" lang="en-US">
  <head>
    <title>Attention Required! | Cloudflare</title>

    <meta charset="UTF-8" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />

    <meta name="robots" content="noindex, nofollow" />

    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <link
      rel="stylesheet"
      id="cf_styles-css"
      href="/cdn-cgi/styles/cf.errors.css"
    />

    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="cf-wrapper">
      <div
        class="cf-alert cf-alert-error cf-cookie-error"
        id="cookie-alert"
        data-translate="enable_cookies"
      >
        Please enable cookies.
      </div>

      <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-header cf-error-overview">
          <h1 data-translate="block_headline">Sorry, you have been blocked</h1>

          <h2 class="cf-subheadline">
            <span data-translate="unable_to_access"
              >You are unable to access</span
            >
            riotgames.com
          </h2>
        </div>
        <div class="cf-section cf-highlight">
          <div class="cf-wrapper">
            <div class="cf-screenshot-container cf-screenshot-full">
              <span class="cf-no-screenshot error"></span>
            </div>
          </div>
        </div>
        <div class="cf-section cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
              <h2 data-translate="blocked_why_headline">
                Why have I been blocked?
              </h2>

              <p data-translate="blocked_why_detail">
                This website is using a security service to protect itself from
                online attacks. The action you just performed triggered the
                security solution. There are several actions that could trigger
                this block including submitting a certain word or phrase, a SQL
                command or malformed data.
              </p>
            </div>

            <div class="cf-column">
              <h2 data-translate="blocked_resolve_headline">
                What can I do to resolve this?
              </h2>

              <p data-translate="blocked_resolve_detail">
                You can email the site owner to let them know you were blocked.
                Please include what you were doing when this page came up and
                the Cloudflare Ray ID found at the bottom of this page.
              </p>
            </div>
          </div>
        </div>
        <div
          class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300"
        ></div>
      </div>
    </div>
  </body>
</html>
'

**Comment by pradishb** [comment]
The cloudflare bypass stopped working around Aug 30 02:00 GMT.

**Comment by pradishb** [comment]
Fixed in 22151a9f0ca3bdc4fc4d7b528915d7cd19a27a87

**Comment by gui-fkb** [comment]
Looks like it is not working again :c
