### ISSUE TITLE
Looks like it is not working again :c

### ISSUE THREAD

**Issue by gui-fkb** [sandbox-pokhara/league-client#50]
Looks like it is not working again :c

_Originally posted by @gui-fkb in https://github.com/sandbox-pokhara/league-client/issues/47#issuecomment-2332928172_

**Comment by pradishb** [comment]
Hello, what error does it return?

**Comment by gui-fkb** [comment]
Returning 403, forbidden: 

'<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.theme-dark{background-color:#222;color:#d9d9d9}body.theme-dark a{color:#fff}body.theme-dark a:hover{color:#ee730a;text-decoration:underline}body.theme-dark .lds-ring div{border-color:#999 transparent transparent}body.theme-dark .font-red{color:#b20f03}body.theme-dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.theme-dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.theme-dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.theme-light{background-color:#fff;color:#313131}body.theme-light a{color:#0051c3}body.theme-light a:hover{color:#ee730a;text-decoration:underline}body.theme-light .lds-ring div{border-color:#595959 transparent transparent}body.theme-light .font-red{color:#fc574a}body.theme-light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.theme-light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.theme-light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.theme-light.feedback-report{border:1px solid #959595}body.feedback-report{border-radius:5px}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem;padding-right:1.5rem;width:100%}.main-content .spacer{margin:2rem 0}.main-content .loading-spinner{height:76.391px}.feedback-content{align-content:space-between;display:inline-grid;height:100vh;margin:0;padding:0}.feedback-content .spacer{margin:0}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}.feedback-content{margin-top:0}}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.feedback-report .main-wrapper{min-height:100vh}.font-red{color:#b20f03}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.pow-button{background-color:#0051c3;border:.063rem solid #0051c3;border-radius:.313rem;color:#fff;font-size:.875rem;line-height:1.313rem;margin:2rem 0;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff;cursor:pointer}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;padding-left:1.5rem;padding-right:1.5rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}.rtl .heading-favicon{margin-left:.5rem;margin-right:0}.rtl #challenge-success-text{background-position:100%;padding-left:0;padding-right:42px}.rtl #challenge-error-text{background-position:100%;padding-left:0;padding-right:34px}.challenge-content .spacer{margin:2rem 0}.challenge-content .loading-spinner{height:76.391px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: \'3\',cZone: "auth.riotgames.com",cType: \'managed\',cNounce: \'92058\',cRay: \'8bfc1de87efd1cef\',cHash: \'71241acb102ff6e\',cUPMDTk: "\\/api\\/v1\\/authorization?__cf_chl_tk=TsIUyX8QLwVYtfjC4suly_F4sqGMMgYy2kne17o60Cc-1725768920-0.0.1.1-5076",cFPWv: \'b\',cTTimeMs: \'1000\',cMTimeMs: \'390000\',cTplV: 5,cTplB: \'cf\',cK: "",fa: "\\/api\\/v1\\/authorization?__cf_chl_f_tk=TsIUyX8QLwVYtfjC4suly_F4sqGMMgYy2kne17o60Cc-1725768920-0.0.1.1-5076",md: "FxCSEgCVCSTAB5dbfZkwe8EM8Pg6g6IzWrD6hH0No3E-1725768920-1.1.1.1-zds_XmUzGQbxOTd8t98.Xi.n8eNmTt.8OgY1qN76_.waIB_AaJ37ENYklInzxqIcXB.XR2V3fyc2TNvzhLe3q0Bh3XgTztESq9cT7yDuh_DyUDe6wWU0PUj8PPDgUCoXDrI3a.RuljEN1.xPYctIC09.SUXNkdwqLqpx2pCg.O._B8UMX49y8WvpnAhBJjj3RfVEqaqcPXiOmI8dVNq5Cwvjyw8q9acemFifV1rTRya4rMqNAMEDvBdgPDbDTvlfJgW.63pyBzCgwTasM0YU7po7BrtgC0vnZjxzfKWnUV8VDMdA_R3BNPU7.5bCxvjwNDUlp9L1XhgcphKG_5xrZ2v3drA8_IZuiw9MQ8BsegmPwqvw__4wCl8e9WknKSQ0Rc8dIj11YvCch4tjA.C4YZCmWsVxqgu.KCEgK4jM99oTute1pnUucAql0xatK6Zz5fDG0oSDWcTUUOe_YONXM31Km3TbFPcSmHmb6mtDTVg7A8XUmMZlqcR7RTl_DtUMKMqGJOaBSXo07uZ2cH7WAS1VoJQdvpx1Vpgyf2H8nEXZ3T8bqks6hven5RejWF_XGMzC.fw0mtGwLB48.jZ2TzHSr2HcwMyOuC9lhxc.p3Gk1Sf4Sdrqkhp_81jvGcGnUfgw5z59QYKE2RHThhLO17QKm4zf2vaULlkRSX0HBj1YxJElogcyo9.li823Ml2J4Wtr0b_ID_QfVYoQz7E1Et97eBqH6FHG_TsYNR3B2o0ebzVra4ebTKMirwagp9MARQZYNCVVArXHLNZBxCKZh6D5jmEh.HWlSbQX1rEzXcUAU2mzfCcVJrDDUjSue2j6G3bxYPSAqZsZhqPwbEbXALuBNnSu8nzCk0iNyIGQKd4BxR2xaXXg3o9.Vw3xsFPFb6UKiF53U8wab470XX_fMl71SpKcbsWrjfv7bb4vJY.oGktTSfLDHJD_RLQfC0YYchJnfryOLkKxoXTg7M8Juuq60avTjAFUe3oiSel_ms53rHvVWtfKqZea5NTn7Iz.OKWlhC_vlKIIz.fk4RfF7agZPyL3UCcT1lQHhS6NRy2I7CUTRvkbzyURmEbpf2o7jHjJ.ClRTXSIQb1YYbz2dxhOse.fAY0vllLQYE4GKH_54Kak7v3aEojShcU8jUOx60OteE9beS5AmgWkNJjuyvHYUlXCK1RgZOEL_cfkDubsBoCwMopJD.O9siEZCsLHcO4taXNfgXskEHrdbaialtQD_uvsG9nm8CVxx6MURtEn4bIQHwAKW3tn6tAkzjw7ne59svOAwn8uC8jNLGaj9NXr6UN6L00EE940PZ64nsEg4wiZbSIn6_PGAtBD3IgrGpr3cHaL.zoxIRrFhOkdYi3CotapPChNTxwDwJmz3RmPsdWO1SBk7uBfJ.Xx_cNd7yaZSPJhzDXiGuWGpfEoECEgSgPeucRWx.zSkhnYiyuoW.ymwW6C6wBfKq3hhKYyoWSK3ew51Ccpz5D0zcEIHdxkr5Kd3qb_u19bCUbvlMxeeF01DPFxYFPkw8HKaxDYgPeDkDeHfvIQIgLbCsE1xN1Dm45OyeSa6d4BahR19wvfWnWAaPjdAvL_TlxeiOBFJX1Vr7bOz_VJQxQcDaGDoO7PveMtYH.rMT9U4Z93358kKmxZ7zJJ_MFB59VQjhnT63joT8IFtmNsjeyM4TXc7EY4Ri7xoCWlK6HcKRbnAefLLYOBvFC82yj2Mz0ZTANiyepXCsLWJhyKk7wzHu4MJ7mwpqum.I9aE3lG.ZOOD2OubRuFlNfod4YC29XwcCK78BV9SC0fjfi0oSE7_Kza4ObIuOVAO8VKi9pi7y5m65YZC0fMkrWJczOffRybCEsk07kYW8T4q6yGRTO0nLgPKP1cyAVVgh5E5qAQ3OaSAdXQfAXh75xbz8_458IG5JRdA9XhwktZmpprESyee7Ok2q5vNvf7glv7KjG5qa4q79WAnMOWKgEwdY5dG3YbRixhrS4yCeSH701wzaXzpaGsSp.MfrFalpTrdSbHP81GCHHzF_EGVe3A5oEVJ397OHI4XZ0p_XSkvowz23DwFU_q1FdrK_k0p9e5_X9epRzG1AKaP_wTXiAMnfe12Ars5zkucbJ3C2gNTkOIx31LK7ucIvI4lkCPd8Agbox93sCwEY407rzA5KRt4Y8.rvDZJ7GNumIJgrw8enFRGgF1OD13TMu37pevlmDwroaJ2dIoewkmSRcrojqalMiRS3PXQ0eUZPHgm4uQZ9Hir6RsBMGbBxmBHDAvLChdBbPRlNuFgUOpdGTFKpk.BxP8fwiqiHVS0yoX01PMrcy774J86SqXe1aS2CJxCxq7_euv7D1dADcDKBJUqHzvwCvRtyDAhvaUMTL8OLU8vsCiSZcJO3MIhc_TdShhqcW6LUL1oq_ZcZ9AGkFC73YCRn8yDlwnRAKj24agLRXjjnMu3hslHGdQKLJrjp00fJb5rwZmm65QQ8ykOnWw.5ympadZh_vxx9fo",mdrd: "oPa55aiwKLF1n1g3pug6rSLGVipe1eoDy8U7R1bC2Zg-1725768920-1.1.1.1-w.8qrcmWpn_og8kmyUIyaRrqcgd52eKyCi5PjCuTTNWy9_UEgrs_6GQVT2pB24.4OHXUr6Ktbuwjt0LE2B4IajIYIebrB911skqM_KjaWDDxWp.R1MIv.m4dUZjgJHx9xqY1m4nE0qTwaUmTyPlyRV3vGv5zcxIW4cKWrbAnO.u1dv7KG2aDDwCr9i_Z8a6rXqSMTjp50CrpmtAsZ9jChmgVEVX2k4IHvorHnZeJz3YUFRQe7NQ.sWmLKTYLRFDUX9jvoUMiC1M86z0QPjkSclPBsYSzrhT4svrkME9bGb3aERoFM4AqzEvxuGIZbw6xebqTippGonuXGd9LxVGPigEXhBe_JAAFniOu_Sl03RCR9BD9BR9_l2UyY1ajGAxca6.2rN7qVm6TkFuMzvgO_JW6.9YAPU1lKnVtppvxqFP6dckxTY3okbHfp6g4ljlCPinMzk27m6n.lH5OOcpRitzbvqScAyAryiY1jZKh_37OteWO1QOn.ctuZMYe04Zr3MQnHi2dSvRzWA6jaUSopMhV59e9aN7ErvrUEGpr3sCVYPnjL12ny2grWr7toz8qOnPFmzEAEH.SyGAY8PlrKDgmkXs7JvHep4L17corGkwqcHHvDgSc5w7PfhBWd5mvV1UPPrfx0jXhrzSTgzDJjtbY_4r5wJZbjKiuRHBYxK2I0wBVnSrD_UiIB.hdS4nhvstM3FB9JOijNdu4QC.9XkL8NULZ6Yg3X40IlRT8Ol3m8ZN4bptnAx4hQa1SEmHW2NOkdFzGnnfu3zsAppMYq5AON59Jv2HbzHnHAaQYa8Mni33BL5JQ4veNohDLkOi3rQlki4aJq.VLVJKnK2KG4i7oE.KHGbHFDIHktQIUY1VJDdxCiqhuH_wtspgXgUCwJQWjApjH5f5BdgBqxvPbV3J2efDDGFtlDXo7FKIJ3zGsZGZlXFEDXDxeYyplypqsVdnV5YuE3n4al6eVKnBuEnboZtcvz3tqYqTNaSP9hjyA.28zTzGqMO_TkvH_nyTt6GjOErkZFUuvZMOYU1mDWPW4qneGq9HeZDs14lvWyyTV623yx9EO6oOg_e_Kf3M6Wbox_01xRHipDHpKtJlcdFUNDqCrt.QgQhdvLQClzM0Wz.XMTwhGYyoSk248O6OeblxLh3w4DMlZbxYYTS9RUVU3erE4GnvOQMMzn_jevz4qH3nbF2Xhd4XOguU.eFv3UXurx6jEiduaXO4nr1MhykCpJ6mVKts.X5SCM1iEgjUwwACLsNALNOTBAbFMHRH9_SQBPmrmIUKFw.X5O.ZpnM38seFUJ37Wlrxd3MlnubPYGbVRScYMj6WH1FQ2MCV92Iy.dfzwJQCNrzURxjt01n1FD56rVQXs4t6RNAy8ndwOT9Zv9.xM9IR67HrST5oKBZ8ScpQXa1ueG0zlo4GcJMX8VAGwRTiRSnVpeiz_mOi3IX.QXeDaBQhkn5NcCfA7GYyuZ69NlnC2vRu0OKhgoPiBte0otvjimsUXi8TvzEVUdIzrXYZBLwzFgT4buJ0JgTEUZ1cXT5YGlHqNYA5.LJn6j1G.w.8PqGNROYuuo9tRhduf_khYYs.yhu.HLPPZKt.M7tsuOFtjtptuZF4Q9wVBY6wR7YzMv9vWNVrO8ITI5zpSVWPiIFNS1ia.t8334XzbcljR5Ssq4oK7vaXe1fRm2yQVs84uklBzjM7yFHODVyLCQyrbmn5chcok8wPzKgAUSHvnhJMWOR_Q56w4y6YKwHAfje66iuqeEFrlmXODz8EnSy08AsbhNSHaTI78kUGBhCUNUewEnPSU0XYOXZhFcjGk3qnQJyoT.mxWGEgoMTVfYwfkJDrHT_SzPssJj77RjIlSFgvWWK82Yysv_VDulTr8Ml92TcqVBFmgPRQmSK459u897saCu0AuonfFw2EcUH9DnRVb180bXBUBqm7XHGVFiyko4i7B8qOGV8o7DnIBU2qFKLh6fAxSYHPcUeDzJbmZYV6dPtVkU7QwQ5DVI1VB_60o0UzMvp95hMth5yD5wyHHLK7MJXGJXyoMa6F.saUwwhTowmDYoOqB.eJhPfdSlydFGSsSNehf02ZU7mK6M3SUvJNOvAlwz6sAxRMoWgVhw5lvQFZ.sAorYWRkMAXyzS3Wx1yvnQC5YTQZKXuUPBG79py1.XtIkM0wlwHiw..Ce3xoys8ZxgQBLWaYjuJjrTa_wuD_EeVAd1EeoafgdI5D8L0wXUlV1tKiBtEWjIfhmdjydsuPX8GJTOyAbyGHhwOmtAubry23hfFwvPhfx9pDoA_pJgTcJ9nubeJVbYJKuWyQS.jlGOeYmDjVrTD5u4.Cq0e_heXritAG3p42qtwNblBbuTVO9VEkxlEVGZXX1z0x4Y1HHhvfIBdr4KJXb60qbH5f.B25FJDtLCxzZCngOENwzUeS8ovVHAv8HFX8ETn7ZFNiKeeuuw",cRq: {ru: \'aHR0cHM6Ly9hdXRoLnJpb3RnYW1lcy5jb20vYXBpL3YxL2F1dGhvcml6YXRpb24=\',ra: \'TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxMV8wIGxpa2UgTWFjIE9TIFgpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS82MC4wLjE1MDIuNzkgTW9iaWxlIFNhZmFyaS81MzcuMzY=\',d: \'X1gMsAyAqru6OsFKICww+KxbsgHwfcK2+WeH26TN9SAK8mn1Qx6WOlOPAPX7d/KcPWkoyYoBomGHen/1ZncPxHgQiC79QaQzVz82IifrP/e6tbqqQp2+hGAMTFJvQ6bbjf//QDGlfyfWEKu3qe0LSKXfm9kcXZp7BilFASI92hHERwxXwnJs3yyUdefhgE2/GU9S8gPSfEZndbcUMgoHOnlk4QZVs7WEjjNqn0ZfPxzYKqspriu1yFJbxbEm24wGLj/C2vRvuN+h9rXWRAcVS5DdnWoe/EXv0NTfnedq0GZVDO25KF15qpCaDl1JofD8O3Oz44kMqfIcir6utfzBeqwD3IVC+2TnmgBqL7ZsDEtkfYX4p6EsebyRim/vQeHIOViAkz/e/vYEhfv8VXaa7+GqOeV/1Xle48cGoZxMn7hNE1HgqsRgypmAlPmrVn+vSILzymlbEsf2VIcbY8HL2X85CtDPLEOF8BJyhiuHvs33WSY0hX7Mq4/lQHCRtkfUwVviXY22UhpjS15U9U3whxFa3siVcJKA8OCAkjfmwATg8jipYzccpTXvETJTSPxG\',t: \'MTcyNTc2ODkyMC4wMDAwMDA=\',cT: Math.floor(Date.now() / 1000),m: \'4DGs481SA744iR6RNP00VMs76bhDbV3N8lqZ/ypzQ/w=\',i1: \'GOyfuvUx9PfgwDfOF0qidw==\',i2: \'FauYSbsM5NJcJbOPb6Lw0A==\',zh: \'bWnw0QKXyr+VDIdhexDX8nPp+nuJ1dv+nsrCfX0UArw=\',uh: \'CrUG3KNFykKFFqJTIw6p8CtMn9JsC358UKZehEvxIQQ=\',hh: \'XEkPTqxdkpsWgjFfGBNYBdSY+bN52e/zfZJXpFYUOyU=\',}};var cpo = document.createElement(\'script\');cpo.src = \'/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8bfc1de87efd1cef\';window._cf_chl_opt.cOgUHash = location.hash === \'\' && location.href.indexOf(\'#\') !== -1 ? \'#\' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === \'\' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf(\'?\') !== -1 ? \'?\' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\\/api\\/v1\\/authorization?__cf_chl_rt_tk=TsIUyX8QLwVYtfjC4suly_F4sqGMMgYy2kne17o60Cc-1725768920-0.0.1.1-5076" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName(\'head\')[0].appendChild(cpo);}());</script></body></html>'

**Comment by pradishb** [comment]
Version 2.1.0 was just released but it needs captcha.
