### ISSUE TITLE
Auth failure 

### ISSUE THREAD

**Issue by devrtex** [sandbox-pokhara/league-client#54]
It gives out the error ,"error":"auth_failure"}', 200) everytime the hcaptcha has been solved even proxy has been implemented.

**Comment by pradishb** [comment]
Hello, most of the captcha services do not work. 2captcha was working for some hours yesterday. It's the only service that I know works. The other solution that works is solving the captcha manually using ValLib's WebServerSolver.

```py
from ValLib.captcha.web import WebServerSolver

login_using_credentials(
    "username",
    "password",
    WebServerSolver().token,
    params=RIOT_CLIENT_AUTH_PARAMS,
    proxy="proxy",
)
```

**Comment by devrtex** [comment]
yes, im using 2captcha, it work at first, an return error "error":"auth_failure"}', 200) after 2-3 requests.

**Comment by pradishb** [comment]
`WebServerSolver` has close to 100% success rate. 2captcha is not reliable.

**Comment by Khaledmohamed1988** [comment]
i tried this and still not working after pop up and solving hcaptcha still 200 response code with auth fail

**Comment by pradishb** [comment]
```py
# captcha_solver is a function that takes rqdata and sitekey as arguments
# and should return a token, ucaptcha is used here, but you can use your
# custom code here
def captcha_solver(rqdata: str, sitekey: str) -> str:
    return solve_captcha(
        "capmonster", # other captcha service might not work
        "...",
        sitekey,
        "https://authenticate.riotgames.com/?client_id=lol&locale=en_US&method=riot_identity&platform=windows",
        rqdata=rqdata,
    )
    ```
    Use this code, it works.

**Comment by pradishb** [comment]
> i tried this and still not working after pop up and solving hcaptcha still 200 response code with auth fail

If you are using `WebServerSolver`. Use the host 127.0.0.1, `WebServerSolver("127.0.0.1")`
